
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.SUPABASE_URL || "https://jxdqcvdwukoensyoauep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZHFjdmR3dWtvZW5zeW9hdWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODc0MTEsImV4cCI6MjA1Njc2MzQxMX0.YHLYWhrIGvQxMxTC_r1s8dsZEJCU95-HOU77gvA7npE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
